version: 2
updates:

  # Config for backend-dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "org.springframework.boot*"
        update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]
    groups:
      backend-dependencies:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
          - "major"

  # Config for docker-compose
  - package-ecosystem: docker-compose
    directory: "/"
    schedule:
      interval: monthly
    groups:
      docker-compose:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
          - "major"
