server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/engine-safari
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    webapp:
      application-path: /camunda
    database:
      type: postgres
      schema-update: true

cibseven:
  webclient:
    authentication:
      # WARNING: This is a development/example secret key.
      # DO NOT use this in production! Generate your own secure secret key.
      jwtSecret: RtURHZ7SQYfLoX902wcjlvduW2qe9g0bjMUczmffjiTjzU9phbv3mK54zHMqeGK6cqgoEBTIUE6RqwvemSqbpD40qUPXVRElvDHGhn4OAEfjeEP2ANah8GJejSA08E820mForcQHBmediqg2DzIrxnDXyf2

